In [ ]:
# Задание 1
# Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

# Задание 2
# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

# Задание 3
# Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

In [5]:
import numpy as np
n = 10
# np.full(10, -1)
np.arange(n, -1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [13]:
p=np.diag(np.arange(n, -1, -1), k=0)
print (p)
sum(sum(p))

[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]


55

In [14]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
from numpy import linalg
linalg.solve(a, b)


array([ 0.46666667,  3.84444444, -5.55555556])

In [ ]:
# Задача 4 домашнего задания
# Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. 
# Остальные столбцы - количество покупок категорий товаров этим пользователем:
# Найдите самого похожего пользователя.
# Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [15]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])


In [20]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )


np.array(users_stats[0])

array([2, 1, 0, 0, 0, 0])

In [52]:
cos_list = []
index_= []
for i, elem in enumerate(users_stats):
    a= np.array(elem)
    b= next_user_stats
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    cos_ = np.dot( a, b ) / ( aLength * bLength )
    cos_list.append (cos_)
    index_.append (i)

    
final=zip(index_,cos_list)
for elem in final:
   
    if max(cos_list) in elem:
        
        print('пользователь номер', elem[0], 'максимально похож с новым пользователем, коррекляция составила', elem [1])
# print (list(final))
# print(max(cos_list))

#     print(elem)

пользователь номер 7 максимально похож с новым пользователем, коррекляция составила 0.9486832980505138
0.9486832980505138
